version: "3"

volumes:
  postgres:
  bundle:

services:
  web:
    build: .
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TRUSTED_IP: 172.19.0.1
    ports:
      - "3000:3000"
    depends_on:
      - db
    # Uncomment for development
    # volumes:
    #   - .:/code
    # # Uncomment when adding/updating gems
    #   # - bundle:/usr/local/bundle
  db:
    image: postgres:9.6.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
