version: "3"

volumes:
  postgres:
  bundle:

services:
  client:
    build: ../elementary-client
    volumes:
      - ../elementary-client:/code
  api:
    image: quay.io/levieindustries/elementary-api:latest
    ports:
      - 3000
    depends_on:
      - db
    # Uncomment for development
    volumes:
      - .:/code
    # Uncomment when adding/updating gems
      # - bundle:/usr/local/bundle
  db:
    image: postgres:10.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432
  lb:
    image: coderiety/consul-lb:master
    environment:
      USE_SSL: '0'
    ports:
      - 80:80
    depends_on:
      - consul
  consul:
    image: consul:1.0.0
    hostname: consul
    ports:
      - 8500:8500
