version: "3"

volumes:
  postgres:
  bundle:

services:
  client:
    image: quay.io/levieindustries/elementary:authing-with-graphql
    # Uncomment for development
    environment:
      WATCH: "1"
    volumes:
      - ../elementary-client/bin:/code/bin
      - ../elementary-client/etc:/code/etc
      - ../elementary-client/src:/code/src
      - ../elementary-client/.eslintrc.json:/code/.eslintrc.json
      - ../elementary-client/.stylelintrc.json:/code/.stylelintrc.json
  api:
    image: quay.io/levieindustries/elementary-api:latest
    ports:
      - 3000
    depends_on:
      - db
    # Uncomment for development
    volumes:
      - .:/code
    # Uncomment when adding/updating gems
      - bundle:/bundle
  db:
    image: postgres:10.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432
  lb:
    image: coderiety/consul-lb:master
    environment:
      USE_SSL: '0'
    ports:
      - 80:80
    depends_on:
      - consul
  consul:
    image: consul:1.0.1
    hostname: consul
    ports:
      - 8500:8500
