default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: elementary_development

test:
  <<: *default
  database: elementary_test

production:
  <<: *default
  database: elementary_production
  username: elementary
  password: <%= ENV['ELEMENTARY_DATABASE_PASSWORD'] %>
